#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
GH_REPO="${GH_REPO:-}" # owner/repo for gh writes; empty = infer from cwd
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
_stdin_died() {
  printf '\n'
  warn "read() returned end-of-file — no keystrokes are reaching this script."
  note "stdin is a tty: $([[ -t 0 ]] && echo yes || echo no)   tty: $(tty 2>/dev/null || echo none)"
  note "parent: $(ps -o comm= -p "$PPID" 2>/dev/null || echo unknown)"
  note "A Claude Code '!' command and a background job both look like this: they"
  note "give the script a terminal but never forward what you type. Run it from a"
  note "Terminal.app or iTerm window instead."
  exit 1
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || _stdin_died
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || _stdin_died
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || _stdin_died
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || _stdin_died
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# _gh_ready — gh installed and authenticated?
_gh_ready() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

# preflight_gh — prove gh can actually reach the repo BEFORE any stage asks for
# a credential. A token that cannot resolve the repo must fail here, not after
# the human has minted a password. Call once, right after banner.
preflight_gh() {
  local out="" rc=0
  if ! command -v gh >/dev/null 2>&1; then
    warn "gh not installed — secrets will be skipped"; return 1
  fi
  if ! gh auth status >/dev/null 2>&1; then
    warn "gh not authenticated — run: gh auth login"; return 1
  fi
  if [[ -n "$GH_REPO" ]]; then
    out=$(gh repo view "$GH_REPO" --json nameWithOwner 2>&1 >/dev/null) || rc=$?
  else
    out=$(gh repo view --json nameWithOwner 2>&1 >/dev/null) || rc=$?
  fi
  (( rc == 0 )) && return 0
  warn "gh cannot reach ${GH_REPO:-the current repo}: ${out%%$'\n'*}"
  note "fix the token scope now, or every secret below will be skipped"
  return 1
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh, targeting
# $GH_REPO when set. Reports gh's own error rather than hiding it: a silent
# "skipped" reads as done and is how a wizard finishes with nothing written.
set_secret() {
  local name="$1" value="$2" err="" rc=0
  if ! _gh_ready; then
    err="gh not installed or not authenticated"; rc=1
  elif [[ -n "$GH_REPO" ]]; then
    err=$(printf '%s' "$value" | gh secret set "$name" --repo "$GH_REPO" 2>&1 >/dev/null) || rc=$?
  else
    err=$(printf '%s' "$value" | gh secret set "$name" 2>&1 >/dev/null) || rc=$?
  fi
  if (( rc == 0 )); then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  err="${err%%$'\n'*}"; [[ -n "$err" ]] || err="gh exited $rc"
  SKIPPED+=("GitHub secret $name — $err")
  warn "skipped GitHub secret $name: $err"
  return 0
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2" err="" rc=0
  if ! _gh_ready; then
    err="gh not installed or not authenticated"; rc=1
  elif [[ -n "$GH_REPO" ]]; then
    err=$(gh variable set "$name" --repo "$GH_REPO" --body "$value" 2>&1 >/dev/null) || rc=$?
  else
    err=$(gh variable set "$name" --body "$value" 2>&1 >/dev/null) || rc=$?
  fi
  if (( rc == 0 )); then
    printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  err="${err%%$'\n'*}"; [[ -n "$err" ]] || err="gh exited $rc"
  SKIPPED+=("GitHub variable $name — $err")
  warn "skipped GitHub variable $name: $err"
  return 0
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
TOTAL_MINUTES=12

# Unblocks W4 (docs/architecture/chunk5-windows.md). Same three homes as the
# Shopify pair (chunk5-w2-handoff.md): GitHub secrets (backup only — no workflow
# reads them) and /srv/connect/env, picked up by a hub restart.
#
# Secrets never touch disk here: ask_secret reads into shell vars, gh reads the
# value on stdin, and the droplet gets it over ssh stdin — never argv, so never
# `ps` or shell history. ENV_FILE sits outside the repo only so ask()'s re-run
# defaults can't pick up a .env in the git tree; nothing writes to it.
ENV_FILE="${HOME}/.bcns-meta-monday-wizard.env"
GH_REPO="bcn-services/bcns"

HUB="https://connect.bcn-services.com"
# Public client ids, read off each dashboard 2026-09-21. Enter keeps them.
META_CLIENT_ID_DEFAULT="__META_APP_ID__"
MONDAY_CLIENT_ID_DEFAULT="642d6119be28135602d7e71a508c665d"   # monday app 12183965
MONDAY_APP_URL="https://bcns-force.monday.com/apps/manage/12183965/app_versions/18044067/sections/appDetails"

# Neither droplet key has a default filename, so -i + IdentitiesOnly (see
# w3-oauth-wizard.sh). -n stops ssh eating this script's stdin.
dssh() { ssh -n -i "$SSH_KEY" -o IdentitiesOnly=yes -o BatchMode=yes "$DROPLET_SSH" "$@"; }
# Same, but stdin is the payload — used only to carry the env lines.
dssh_stdin() { ssh -i "$SSH_KEY" -o IdentitiesOnly=yes -o BatchMode=yes "$DROPLET_SSH" "$@"; }

hub_pid() { dssh 'systemctl show -p MainPID --value bcns-app@connect' | tr -d '[:space:]'; }

# Gate value from the RUNNING process — the file can differ from what's loaded.
# OAUTH_APPROVED_SOURCES is a list of names, not a secret.
probe_gate() {
  dssh 'p=$(systemctl show -p MainPID --value bcns-app@connect)
        [ -n "$p" ] && [ "$p" != 0 ] || { echo "unit NOT RUNNING"; exit 0; }
        v=$(tr "\0" "\n" < /proc/$p/environ | grep "^OAUTH_APPROVED_SOURCES=" || true)
        echo "pid $p: ${v:-OAUTH_APPROVED_SOURCES unset}"' 2>&1 || echo "(probe failed)"
}

# check_secret NAME VALUE ID — catch the two likely paste mistakes before storing.
check_secret() {
  [[ -n "$2" ]] || { warn "$1 is empty — stopping."; exit 1; }
  [[ "$2" != "$3" ]] || { warn "$1 equals the client id — that's the id, not the secret. Stopping."; exit 1; }
  [[ "$2" =~ ^[0-9a-f]{32}$ ]] || warn "$1 is not 32 hex chars (${#2} chars). Unusual — check you copied the right field."
}

[[ -t 0 ]] || {
  warn "No terminal on stdin — every prompt would read EOF and come back empty."
  note "A Claude Code '!' command looks like this. Run it in Terminal or iTerm:"
  note "  cd ~/bcns && GITHUB_TOKEN= ./meta-monday-secrets-wizard.sh"
  exit 1
}
banner "Chunk 5 / W4 unblock — Meta + Monday OAuth secrets"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — GitHub and the droplet" 2
if ! preflight_gh; then
  warn "gh can't reach ${GH_REPO}. Did you run it with GITHUB_TOKEN= in front?"
  exit 1
fi
say "gh reaches ${GH_REPO}."
ask DROPLET_SSH "Droplet ssh target [root@146.190.138.141]:"
DROPLET_SSH="${DROPLET_SSH:-root@146.190.138.141}"
ask SSH_KEY "Private key for it [~/.ssh/id_ed25519_bcns]:"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/id_ed25519_bcns}"
SSH_KEY="${SSH_KEY/#\~/$HOME}"
[[ -f "$SSH_KEY" ]] || { warn "no such key: $SSH_KEY"; exit 1; }
WHO="$(dssh 'id -un' 2>/dev/null | tr -d '[:space:]' || true)"
[[ -n "$WHO" ]] || { warn "ssh ${DROPLET_SSH} with ${SSH_KEY} failed."; exit 1; }
say "ssh ok, logged in as: ${WHO}"
say "Env keys in /srv/connect/env now (names only):"
dssh 'grep -oE "^[A-Z_]+=" /srv/connect/env | tr -d "=" | sort' || { warn "could not read /srv/connect/env"; exit 1; }
say "Gate: $(probe_gate)"
note "expected: OAUTH_APPROVED_SOURCES=shopify. This wizard does not change it."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Meta — App ID and App Secret" 4
[[ "$META_CLIENT_ID_DEFAULT" == __* ]] && META_CLIENT_ID_DEFAULT=""
step "developers.facebook.com → the bcns app → App settings → Basic."
step "App ID is public. App Secret: click Show, re-enter your Meta password, copy it."
open_url "https://developers.facebook.com/apps"
ask META_CLIENT_ID "Meta App ID${META_CLIENT_ID_DEFAULT:+ [$META_CLIENT_ID_DEFAULT]}:"
META_CLIENT_ID="${META_CLIENT_ID:-$META_CLIENT_ID_DEFAULT}"
[[ "$META_CLIENT_ID" =~ ^[0-9]+$ ]] || { warn "a Meta App ID is all digits — got '${META_CLIENT_ID}'. Stopping."; exit 1; }
ask_secret META_CLIENT_SECRET "Meta App Secret (will not echo):"
check_secret META_CLIENT_SECRET "$META_CLIENT_SECRET" "$META_CLIENT_ID"
set_secret META_CLIENT_ID "$META_CLIENT_ID"
set_secret META_CLIENT_SECRET "$META_CLIENT_SECRET"
note "GitHub also holds META_APP_SECRET (2026-09-18) — the pre-pattern name. Nothing"
note "reads it. Delete it once you're happy: GITHUB_TOKEN= gh secret delete META_APP_SECRET --repo ${GH_REPO}"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Monday — Client ID and Client Secret" 3
step "monday Developer Center → bcns Connect → General settings → App Credentials."
step "Copy Client Secret — NOT the Signing Secret below it."
open_url "$MONDAY_APP_URL"
ask MONDAY_CLIENT_ID "Monday Client ID [${MONDAY_CLIENT_ID_DEFAULT}]:"
MONDAY_CLIENT_ID="${MONDAY_CLIENT_ID:-$MONDAY_CLIENT_ID_DEFAULT}"
ask_secret MONDAY_CLIENT_SECRET "Monday Client Secret (will not echo):"
check_secret MONDAY_CLIENT_SECRET "$MONDAY_CLIENT_SECRET" "$MONDAY_CLIENT_ID"
set_secret MONDAY_CLIENT_ID "$MONDAY_CLIENT_ID"
set_secret MONDAY_CLIENT_SECRET "$MONDAY_CLIENT_SECRET"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Hub env on the droplet + restart" 3
say "Upserts four lines into /srv/connect/env (replaces any existing line per key),"
say "then restarts bcns-app@connect. OAUTH_APPROVED_SOURCES is not touched — the"
say "hub reads nothing for meta/monday until W4 ships, so this is invisible."
if ! confirm "Write META_/MONDAY_ CLIENT_ID + CLIENT_SECRET to the droplet and restart?"; then
  SKIPPED+=("droplet env not written — re-run and say yes at stage 4")
  unset META_CLIENT_SECRET MONDAY_CLIENT_SECRET
  finish; exit 0
fi
OLD_PID="$(hub_pid)"
# The payload rides ssh stdin; the remote script reads it, drops old lines for
# those keys, appends the new ones. printf is a builtin, so no argv exposure here.
printf 'META_CLIENT_ID=%s\nMETA_CLIENT_SECRET=%s\nMONDAY_CLIENT_ID=%s\nMONDAY_CLIENT_SECRET=%s\n' \
  "$META_CLIENT_ID" "$META_CLIENT_SECRET" "$MONDAY_CLIENT_ID" "$MONDAY_CLIENT_SECRET" |
  dssh_stdin 'set -e; f=/srv/connect/env; new=$(cat)
    for k in META_CLIENT_ID META_CLIENT_SECRET MONDAY_CLIENT_ID MONDAY_CLIENT_SECRET; do
      sed -i "/^$k=/d" "$f"; done
    printf "%s\n" "$new" >> "$f"
    sudo -n systemctl restart bcns-app@connect && sleep 2 && systemctl is-active bcns-app@connect'
unset META_CLIENT_SECRET MONDAY_CLIENT_SECRET
NEW_PID="$(hub_pid)"
echo
say "pid before: ${OLD_PID:-none}   pid after: ${NEW_PID:-none}"
if [[ -z "$NEW_PID" || "$NEW_PID" == 0 ]]; then
  warn "hub is NOT running. Check: journalctl -u bcns-app@connect -n 50"; exit 1
elif [[ "$NEW_PID" == "$OLD_PID" ]]; then
  warn "SAME pid — the restart did not happen, the new env is not loaded."; exit 1
fi
say "new pid — restart confirmed."
say "Keys loaded in the running process (names only):"
dssh "tr '\\0' '\\n' < /proc/${NEW_PID}/environ | grep -oE '^(META|MONDAY)_[A-Z_]+=' | tr -d '=' | sort"
note "expected: META_CLIENT_ID META_CLIENT_SECRET MONDAY_CLIENT_ID MONDAY_CLIENT_SECRET"
say "Gate: $(probe_gate)"
note "expected: still OAUTH_APPROVED_SOURCES=shopify — no meta, no monday."
say "Health: $(curl -sS -o /dev/null -w '%{http_code}' "${HUB}/api/health" 2>&1 || echo 'request failed')"
note "expected: 200"
pause

finish
say "W4 can start: every value it needs is on the droplet and backed up in GitHub."
