#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
GH_REPO="${GH_REPO:-}" # owner/repo for gh writes; empty = infer from cwd
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
_stdin_died() {
  printf '\n'
  warn "read() returned end-of-file — no keystrokes are reaching this script."
  note "stdin is a tty: $([[ -t 0 ]] && echo yes || echo no)   tty: $(tty 2>/dev/null || echo none)"
  note "parent: $(ps -o comm= -p "$PPID" 2>/dev/null || echo unknown)"
  note "A Claude Code '!' command and a background job both look like this: they"
  note "give the script a terminal but never forward what you type. Run it from a"
  note "Terminal.app or iTerm window instead."
  exit 1
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || _stdin_died
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || _stdin_died
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || _stdin_died
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || _stdin_died
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# _gh_ready — gh installed and authenticated?
_gh_ready() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

# preflight_gh — prove gh can actually reach the repo BEFORE any stage asks for
# a credential. A token that cannot resolve the repo must fail here, not after
# the human has minted a password. Call once, right after banner.
preflight_gh() {
  local out="" rc=0
  if ! command -v gh >/dev/null 2>&1; then
    warn "gh not installed — secrets will be skipped"; return 1
  fi
  if ! gh auth status >/dev/null 2>&1; then
    warn "gh not authenticated — run: gh auth login"; return 1
  fi
  if [[ -n "$GH_REPO" ]]; then
    out=$(gh repo view "$GH_REPO" --json nameWithOwner 2>&1 >/dev/null) || rc=$?
  else
    out=$(gh repo view --json nameWithOwner 2>&1 >/dev/null) || rc=$?
  fi
  (( rc == 0 )) && return 0
  warn "gh cannot reach ${GH_REPO:-the current repo}: ${out%%$'\n'*}"
  note "fix the token scope now, or every secret below will be skipped"
  return 1
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh, targeting
# $GH_REPO when set. Reports gh's own error rather than hiding it: a silent
# "skipped" reads as done and is how a wizard finishes with nothing written.
set_secret() {
  local name="$1" value="$2" err="" rc=0
  if ! _gh_ready; then
    err="gh not installed or not authenticated"; rc=1
  elif [[ -n "$GH_REPO" ]]; then
    err=$(printf '%s' "$value" | gh secret set "$name" --repo "$GH_REPO" 2>&1 >/dev/null) || rc=$?
  else
    err=$(printf '%s' "$value" | gh secret set "$name" 2>&1 >/dev/null) || rc=$?
  fi
  if (( rc == 0 )); then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  err="${err%%$'\n'*}"; [[ -n "$err" ]] || err="gh exited $rc"
  SKIPPED+=("GitHub secret $name — $err")
  warn "skipped GitHub secret $name: $err"
  return 0
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2" err="" rc=0
  if ! _gh_ready; then
    err="gh not installed or not authenticated"; rc=1
  elif [[ -n "$GH_REPO" ]]; then
    err=$(gh variable set "$name" --repo "$GH_REPO" --body "$value" 2>&1 >/dev/null) || rc=$?
  else
    err=$(gh variable set "$name" --body "$value" 2>&1 >/dev/null) || rc=$?
  fi
  if (( rc == 0 )); then
    printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  err="${err%%$'\n'*}"; [[ -n "$err" ]] || err="gh exited $rc"
  SKIPPED+=("GitHub variable $name — $err")
  warn "skipped GitHub variable $name: $err"
  return 0
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# sb-bridge: remove after SB migrates to bcns Connect
#
# Points SB (fa8a00-11) at the custom app bcns-data-2 until bcns Connect passes
# review: sets SHOPIFY_ALT_* on the hub and the worker, then connects SB.
# bcns-data-2 (429656047617, single-store custom distribution) replaced bcns-data
# (422420021249) on 2026-09-29: the old app's multi-store Plus-org install link
# could not be refreshed. config.app = 'bcns-data' is still the marker; it only
# means "use the SHOPIFY_ALT_* pair", so the swap needed no code change.
#
# Run from ~/bcns in Terminal.app or iTerm (not a Claude `!` command):
#   bash sb-shopify-bridge-wizard.sh
#
# Re-set recipe: re-run this wizard. The secret stays re-fetchable from the Dev
# Dashboard (bcns-data-2 → Settings → Client secret) and lives in Secret Manager.

set +x   # never trace: the secret passes through printf below

TOTAL_STAGES=3
TOTAL_MINUTES=15

# The secret is NEVER written to disk here. ENV_FILE points outside the repo so
# ask's re-run defaults cannot create or read a .env inside a git tree.
ENV_FILE="${HOME}/.bcns-sb-bridge-wizard.env"

HUB="https://connect.bcn-services.com"
ALT_SHOP="fa8a00-11.myshopify.com"             # permanent domain, NOT the saunaboy-2 admin handle
ALT_CLIENT_ID="a806948335f634ba45b229e12813a95a" # bcns-data-2, public
ALT_APP_ID=429656047617
PROJECT=bcns-leads
REGION=us-east4
JOB=bcns-data-worker
RUNTIME="bcns-data-worker@${PROJECT}.iam.gserviceaccount.com"
ALT_SECRET_NAME=SHOPIFY_ALT_CLIENT_SECRET

# -n: never forward this script's stdin to the remote (see w3-oauth-wizard.sh dssh).
dssh() { ssh -n -i "$SSH_KEY" -o IdentitiesOnly=yes -o BatchMode=yes "$DROPLET_SSH" "$@"; }
# The one call that DOES pipe stdin: the secret goes over ssh's stdin, never argv.
dssh_stdin() { ssh -i "$SSH_KEY" -o IdentitiesOnly=yes -o BatchMode=yes "$DROPLET_SSH" "$@"; }
hub_pid() { dssh 'systemctl show -p MainPID --value bcns-app@connect' | tr -d '[:space:]'; }

# Hub on the new ALT pair but worker on the old one: an SB connect in that window
# mints a token the worker cannot refresh. Any exit between the two says so.
HUB_SET=0; WORKER_SET=0
on_exit() {
  (( HUB_SET == 1 && WORKER_SET == 0 )) || return 0
  printf '\n%s⚠ THE HUB HAS THE NEW ALT VARS BUT THE WORKER DOES NOT%s\n' "$RED" "$RESET"
  printf '  Re-run this script before SB connects. Do NOT connect SB until it finishes.\n\n'
}
trap on_exit EXIT

banner "SB Shopify bridge — connect fa8a00-11 through bcns-data-2"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Hub — replace the three ALT vars and restart" 6
ask DROPLET_SSH "Droplet ssh target [root@146.190.138.141]:"
DROPLET_SSH="${DROPLET_SSH:-root@146.190.138.141}"
ask SSH_KEY "Private key for it [~/.ssh/id_ed25519_bcns]:"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/id_ed25519_bcns}"
SSH_KEY="${SSH_KEY/#\~/$HOME}"
write_env DROPLET_SSH "$DROPLET_SSH"; write_env SSH_KEY "$SSH_KEY"
[[ -f "$SSH_KEY" ]] || { warn "no such key: $SSH_KEY"; exit 1; }
WHO="$(dssh 'id -un' 2>/dev/null | tr -d '[:space:]' || true)"
[[ -n "$WHO" ]] || { warn "ssh ${DROPLET_SSH} with ${SSH_KEY} failed."; exit 1; }
say "ssh ok, logged in as: ${WHO}"
say "ALT keys on the droplet now (names; SHOP and CLIENT_ID values are public):"
dssh 'grep -E "^SHOPIFY_ALT_(SHOP|CLIENT_ID)=" /srv/connect/env; grep -oE "^SHOPIFY_ALT_CLIENT_SECRET=" /srv/connect/env' || note "(none)"
echo
open_url "https://dev.shopify.com/dashboard/235106100/apps/${ALT_APP_ID}/settings"
step "bcns-data-2 (NOT bcns-data) → Settings → Client secret: use the COPY button."
warn "Do not click Show. Nothing reads the secret but this prompt; it is not echoed or saved."
ALT_SECRET=""
read -rsp "  ${BOLD}Paste the bcns-data-2 client secret:${RESET} " ALT_SECRET || _stdin_died
printf '\n'
pbcopy </dev/null 2>/dev/null || true   # clear the clipboard copy of the secret
ALT_SECRET="${ALT_SECRET//[[:space:]]/}" # worker envStr does not trim
[[ -n "$ALT_SECRET" ]] || { warn "the secret is required."; exit 1; }
[[ "$ALT_SECRET" == shpss_* ]] || warn "that does not start with shpss_ — check you copied the secret."

PID_BEFORE="$(hub_pid || true)"
say "hub pid before: ${PID_BEFORE:-none}"
confirm "Replace SHOPIFY_ALT_SHOP / _CLIENT_ID / _CLIENT_SECRET in /srv/connect/env and restart the hub?" \
  || { say "nothing changed."; exit 0; }
HUB_SET=1
# Stage stdin first (an ssh drop leaves env untouched), keep the FIRST backup only,
# then build env.tmp = env minus old ALT lines + new three, and swap atomically.
# The secret rides stdin.
printf 'SHOPIFY_ALT_SHOP=%s\nSHOPIFY_ALT_CLIENT_ID=%s\nSHOPIFY_ALT_CLIENT_SECRET=%s\n' \
  "$ALT_SHOP" "$ALT_CLIENT_ID" "$ALT_SECRET" |
  dssh_stdin 'set -e; umask 077; cd /srv/connect
    cat > env.new
    [ "$(grep -c "^SHOPIFY_ALT_" env.new)" = 3 ] || { echo "staged file incomplete, env untouched" >&2; rm -f env.new; exit 1; }
    [ -e env.bak-sb-rotate ] || cp -p env env.bak-sb-rotate
    { grep -v "^SHOPIFY_ALT_" env || true; } > env.tmp
    [ -z "$(tail -c1 env.tmp)" ] || echo >> env.tmp
    cat env.new >> env.tmp
    chown --reference=env env.tmp; chmod --reference=env env.tmp
    mv env.tmp env; rm -f env.new
    sudo -n systemctl restart bcns-app@connect; sleep 2; systemctl is-active bcns-app@connect'
PID_AFTER="$(hub_pid || true)"
say "hub pid after:  ${PID_AFTER:-none}"
if [[ -z "$PID_AFTER" || "$PID_AFTER" == 0 || "$PID_AFTER" == "$PID_BEFORE" ]]; then
  warn "no NEW pid — the hub did not restart onto the new env. Stopping."; exit 1
fi
say "ALT vars in the RUNNING process (SHOP/CLIENT_ID values, secret name only):"
RUNNING_ENV="$(dssh "tr '\\0' '\\n' < /proc/${PID_AFTER}/environ | grep -E '^SHOPIFY_ALT_(SHOP|CLIENT_ID)=' ; tr '\\0' '\\n' < /proc/${PID_AFTER}/environ | grep -oE '^SHOPIFY_ALT_CLIENT_SECRET=' ; true")"
printf '%s\n' "$RUNNING_ENV" | sed 's/^/    /'
for want in "SHOPIFY_ALT_SHOP=${ALT_SHOP}" "SHOPIFY_ALT_CLIENT_ID=${ALT_CLIENT_ID}" "SHOPIFY_ALT_CLIENT_SECRET="; do
  grep -qxF "$want" <<<"$RUNNING_ENV" || { warn "running hub is missing: ${want}  — stopping before the worker."; exit 1; }
done
say "${GREEN}✓ all three ALT vars live on the hub${RESET}"
note "first-run env kept at /srv/connect/env.bak-sb-rotate (holds the previous secret — delete once SB syncs)."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Worker — new secret version + the two public vars" 4
command -v gcloud >/dev/null 2>&1 || { warn "gcloud is not installed."; exit 1; }
note "account: $(gcloud config get-value account 2>/dev/null || echo '(none)')"
gcloud run jobs describe "$JOB" --project "$PROJECT" --region "$REGION" --format='value(metadata.name)' >/dev/null || {
  warn "gcloud cannot read ${JOB} (try: gcloud auth login)."; exit 1; }
confirm "Add a new ${ALT_SECRET_NAME} version and point ${JOB} at bcns-data-2?" \
  || { warn "worker unchanged — do NOT connect SB until this runs."; exit 1; }
if gcloud secrets describe "$ALT_SECRET_NAME" --project "$PROJECT" >/dev/null 2>&1; then
  printf '%s' "$ALT_SECRET" | gcloud secrets versions add "$ALT_SECRET_NAME" --project "$PROJECT" --data-file=- >/dev/null
  note "added a new version of ${ALT_SECRET_NAME}."
else
  printf '%s' "$ALT_SECRET" | gcloud secrets create "$ALT_SECRET_NAME" --project "$PROJECT" \
    --replication-policy automatic --data-file=- >/dev/null
  note "created ${ALT_SECRET_NAME}."
fi
unset ALT_SECRET
gcloud secrets add-iam-policy-binding "$ALT_SECRET_NAME" --project "$PROJECT" \
  --member "serviceAccount:${RUNTIME}" --role roles/secretmanager.secretAccessor >/dev/null
# --update-* merges; --set-* would wipe the job's other env. :latest picks up the new version.
gcloud run jobs update "$JOB" --project "$PROJECT" --region "$REGION" \
  --update-env-vars "SHOPIFY_ALT_SHOP=${ALT_SHOP},SHOPIFY_ALT_CLIENT_ID=${ALT_CLIENT_ID}" \
  --update-secrets "${ALT_SECRET_NAME}=${ALT_SECRET_NAME}:latest" >/dev/null
note "read back from the live job:"
gcloud run jobs describe "$JOB" --project "$PROJECT" --region "$REGION" --format=yaml |
  grep -i -A2 'SHOPIFY_ALT' || warn "no SHOPIFY_ALT entries came back — check the job by hand."
WORKER_SET=1
note "deploy-worker.yml only swaps the image, so these survive the next deploy."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Connect SB" 5
say "A custom app must be installed from its install link first: the hub's Connect"
say "alone shows 'The installation link for this app is invalid' until it is."
step "Sign in at ${HUB} as an sb owner, enter ${ALT_SHOP} on the Shopify card, press Connect."
step "Within 15 minutes, in the same browser: Partners → bcns-data-2 → Distribution → open the install link."
open_url "https://partners.shopify.com/5179321/apps/${ALT_APP_ID}/distribution"
step "The grant says 'exclusive to your store'. Install. You land on ${HUB}/?connected=shopify."
note "already installed: Connect alone completes (an installed app auto-approves)."
note "on connect-failed: ssh -i ${SSH_KEY} ${DROPLET_SSH} 'journalctl -u bcns-app@connect --since \"10 min ago\" | grep -i reject'"
pause "Connected? Press Enter."

finish
say "SB is on bcns-data-2. The card fills on the next worker tick (≤ 10 min)."
say "Retirement order: hub ALT vars off → SB reconnects on bcns Connect → uninstall bcns-data-2 → worker ALT vars off → delete sb-bridge code."
