#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
GH_REPO="${GH_REPO:-}" # owner/repo for gh writes; empty = infer from cwd
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
_stdin_died() {
  printf '\n'
  warn "read() returned end-of-file — no keystrokes are reaching this script."
  note "stdin is a tty: $([[ -t 0 ]] && echo yes || echo no)   tty: $(tty 2>/dev/null || echo none)"
  note "parent: $(ps -o comm= -p "$PPID" 2>/dev/null || echo unknown)"
  note "A Claude Code '!' command and a background job both look like this: they"
  note "give the script a terminal but never forward what you type. Run it from a"
  note "Terminal.app or iTerm window instead."
  exit 1
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || _stdin_died
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || _stdin_died
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || _stdin_died
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || _stdin_died
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# _gh_ready — gh installed and authenticated?
_gh_ready() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

# preflight_gh — prove gh can actually reach the repo BEFORE any stage asks for
# a credential. A token that cannot resolve the repo must fail here, not after
# the human has minted a password. Call once, right after banner.
preflight_gh() {
  local out="" rc=0
  if ! command -v gh >/dev/null 2>&1; then
    warn "gh not installed — secrets will be skipped"; return 1
  fi
  if ! gh auth status >/dev/null 2>&1; then
    warn "gh not authenticated — run: gh auth login"; return 1
  fi
  if [[ -n "$GH_REPO" ]]; then
    out=$(gh repo view "$GH_REPO" --json nameWithOwner 2>&1 >/dev/null) || rc=$?
  else
    out=$(gh repo view --json nameWithOwner 2>&1 >/dev/null) || rc=$?
  fi
  (( rc == 0 )) && return 0
  warn "gh cannot reach ${GH_REPO:-the current repo}: ${out%%$'\n'*}"
  note "fix the token scope now, or every secret below will be skipped"
  return 1
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh, targeting
# $GH_REPO when set. Reports gh's own error rather than hiding it: a silent
# "skipped" reads as done and is how a wizard finishes with nothing written.
set_secret() {
  local name="$1" value="$2" err="" rc=0
  if ! _gh_ready; then
    err="gh not installed or not authenticated"; rc=1
  elif [[ -n "$GH_REPO" ]]; then
    err=$(printf '%s' "$value" | gh secret set "$name" --repo "$GH_REPO" 2>&1 >/dev/null) || rc=$?
  else
    err=$(printf '%s' "$value" | gh secret set "$name" 2>&1 >/dev/null) || rc=$?
  fi
  if (( rc == 0 )); then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  err="${err%%$'\n'*}"; [[ -n "$err" ]] || err="gh exited $rc"
  SKIPPED+=("GitHub secret $name — $err")
  warn "skipped GitHub secret $name: $err"
  return 0
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2" err="" rc=0
  if ! _gh_ready; then
    err="gh not installed or not authenticated"; rc=1
  elif [[ -n "$GH_REPO" ]]; then
    err=$(gh variable set "$name" --repo "$GH_REPO" --body "$value" 2>&1 >/dev/null) || rc=$?
  else
    err=$(gh variable set "$name" --body "$value" 2>&1 >/dev/null) || rc=$?
  fi
  if (( rc == 0 )); then
    printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  err="${err%%$'\n'*}"; [[ -n "$err" ]] || err="gh exited $rc"
  SKIPPED+=("GitHub variable $name — $err")
  warn "skipped GitHub variable $name: $err"
  return 0
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
TOTAL_MINUTES=28

# Secrets are NEVER written to disk by this wizard — ask_secret reads them into
# shell vars only. ENV_FILE points outside the repo purely so `ask`'s re-run
# defaults can't pick up (or create) a .env inside a git tree.
ENV_FILE="${HOME}/.bcns-w3-wizard.env"

SLUG="bcns-oauth-test"
HUB="https://connect.bcn-services.com"
DEFAULT_SHOP="bcns-data-dev.myshopify.com"   # the org's only dev store
# Read off the Dev Dashboard 2026-09-18 for app "bcns Connect" (425274376193),
# active version bcns-connect-4. Client ID is public — it rides in the install URL.
APP_CLIENT_ID="a87d4fe4a4c2b0a57d370e24f28a12bf"
API_VERSION="2026-07"   # platform/worker/src/connectors/shopify-url.ts:3
GATE_FLIPPED=0


# ponytail: DATABASE_URL and the Shopify tokens are passed as argv to psql/curl,
# so they're briefly visible in `ps` to this user. Single-user laptop, accepted.
# Upgrade path: a ~/.pgpass entry and curl --config if this ever runs shared.

# host:port of a postgres URL, with the credentials stripped off.
db_host() { printf '%s' "$1" | sed -E 's#^[^@]*@##; s#[/?].*$##'; }

# The one credential-free probe of the approval gate. start/route.ts checks
# oauthEnabled (line 30) BEFORE requireOwner (line 33), so a signed-out request
# distinguishes the two states by where it redirects.
# A signed-out curl CANNOT read this gate. middleware.ts matches /api/oauth/*
# (deliberately — the bounce is the first half of the owner check), so it 307s to
# /login before the route handler runs, and answers "/login" whether the gate is
# open or shut. Verified live on 2026-09-19 with the gate closed.
#
# Read the RUNNING process environment instead. systemd reads EnvironmentFile only
# at process start, so this also catches an env file edited without a restart —
# which the file itself would not show.
probe_gate() {
  dssh 'p=$(systemctl show -p MainPID --value bcns-app@connect)
        if [ -z "$p" ] || [ "$p" = 0 ]; then echo "unit NOT RUNNING"; exit 0; fi
        v=$(tr "\0" "\n" < /proc/$p/environ | grep "^OAUTH_APPROVED_SOURCES=" || true)
        echo "pid $p: ${v:-OAUTH_APPROVED_SOURCES unset (gate CLOSED)}"' 2>&1 \
    || echo "(probe failed)"
}

# shop_gql TOKEN QUERY — one Admin GraphQL call, raw response to stdout.
shop_gql() {
  curl -sS -X POST "https://${DEV_SHOP}/admin/api/${API_VERSION}/graphql.json" \
    -H "X-Shopify-Access-Token: $1" -H 'Content-Type: application/json' \
    --data "$(printf '{"query":%s}' "$(printf '%s' "$2" | sed 's/\\/\\\\/g; s/"/\\"/g; s/^/"/; s/$/"/')")" \
    2>&1 || echo '(request failed)'
}

# If the gate is left open when the script exits for any reason, say so loudly.
# Shipping dark is intended until W6, and a crash must not leave it live.
on_exit() {
  (( GATE_FLIPPED == 1 )) || return 0
  printf '\n%s⚠ THE OAUTH GATE IS STILL OPEN ON THE DROPLET%s\n' "$RED" "$RESET"
  printf '  Revert it by hand before you walk away:\n\n'
  printf '    ssh -i %s %s '\''sed -i "/^OAUTH_APPROVED_SOURCES=/d" /srv/connect/env && sudo -n systemctl restart bcns-app@connect'\''\n\n' \
    "${SSH_KEY:-$HOME/.ssh/id_ed25519_bcns}" "${DROPLET_SSH:-<droplet>}"
}
# Neither droplet key has a default filename (~/.ssh/id_ed25519 is the school
# key) and ssh-agent holds no identities, so plain `ssh host` offers the wrong
# key and the droplet answers "Permission denied (publickey)". -i fixes it;
# IdentitiesOnly stops ssh trying the others first and tripping MaxAuthTries.
# -n is load-bearing: without it ssh reads this script's stdin and forwards it
# to the remote command, swallowing whatever you have typed. Proved 2026-09-19
# on a pty — two buffered lines vanished without -n and survived with it. This
# is what made stage 3 fly past its prompts and the password reads come back
# blank. No dssh call pipes anything in, so nothing needs stdin.
dssh() { ssh -n -i "$SSH_KEY" -o IdentitiesOnly=yes -o BatchMode=yes "$DROPLET_SSH" "$@"; }

trap on_exit EXIT


# Every prompt helper here ends in `read ... || true`, so with no terminal on
# stdin each one returns an empty string and the script keeps going: the
# password reads blank, and every confirm() reads blank, fails ^[Yy] and
# declines. A Claude Code `!` command has no stdin, which is exactly this.
[[ -t 0 ]] || {
  warn "No terminal on stdin — every prompt would read EOF and come back empty."
  note "A Claude Code '!' command looks like this. Run it in Terminal or iTerm:"
  note "  cd ~/bcns && ./w3-oauth-wizard.sh"
  exit 1
}
banner "Chunk 5 / W3 — Shopify dev-store install"
say "build 2026-09-19c · tty $(tty 2>/dev/null || echo none) · parent $(ps -o comm= -p "$PPID" 2>/dev/null || echo unknown)"

# ── preflight (not a stage) ───────────────────────────────────────────────
# Stage 1 created and verified the tenant on 2026-09-19 and is gone. Only the
# database connection survives it, because stages 3, 4 and 6 read
# data.source_tokens / data.connector_schedule — that is the window's DONE WHEN.
#
# Every part of the connection except the password is fixed and non-secret, read
# off the Supabase Connect panel (Session pooler) on 2026-09-19. The direct host
# db.<ref>.supabase.co is IPv6-only and does not resolve on an IPv4 network, so
# the pooler is the only one that works from here.
command -v psql >/dev/null 2>&1 || { warn "psql not found — install it first (brew install libpq)"; exit 1; }

if [[ -n "${DATABASE_URL:-}" ]]; then
  # .env.local carries the DIRECT URL, db.<ref>.supabase.co, which is IPv6-only
  # and does not resolve on an IPv4 network. Same database and same password —
  # only the host and the username differ — so rewrite it to the session pooler
  # rather than making anyone hand-edit a credential. Region read off the
  # Connect panel 2026-09-19. The password half is matched greedily so a
  # password containing '@' still splits at the right place.
  if [[ "$DATABASE_URL" =~ ^postgres(ql)?://([^:/]+):(.+)@db\.([a-z0-9]+)\.supabase\.co:([0-9]+)/(.+)$ ]]; then
    DATABASE_URL="postgresql://${BASH_REMATCH[2]}.${BASH_REMATCH[4]}:${BASH_REMATCH[3]}@aws-0-us-east-1.pooler.supabase.com:5432/${BASH_REMATCH[6]}"
    note "direct host is IPv6-only — rewritten to the session pooler."
  fi
  pg() { psql "$DATABASE_URL" "$@"; }
  PG_TARGET="$(db_host "$DATABASE_URL")"
  say "DATABASE_URL taken from the environment: ${PG_TARGET}"
else
  export PGHOST="aws-0-us-east-1.pooler.supabase.com"
  export PGPORT="5432"
  export PGUSER="postgres.cnsxbglhredokjbvudfd"
  export PGDATABASE="postgres"
  pg() { psql "$@"; }
  PG_TARGET="${PGHOST}:${PGPORT}"
  say "Database: ${PGUSER} @ ${PG_TARGET}"
  # Three ways in, cheapest first. The prompt is last because it is the one that
  # has actually failed: on 2026-09-19 three `read -rs` in a row returned zero
  # characters in a real Terminal window.
  #
  # ~/.pgpass is the standard Postgres credential file. psql reads it on its own,
  # so with it in place nothing here asks for anything. Create it once:
  #   umask 077; printf '%s\n' \
  #     'aws-0-us-east-1.pooler.supabase.com:5432:postgres:postgres.cnsxbglhredokjbvudfd:YOURPASSWORD' \
  #     >> ~/.pgpass
  if [[ -n "${PGPASSWORD:-}" ]]; then
    say "password: taken from PGPASSWORD — note this OVERRIDES ~/.pgpass."
  elif [[ -f "$HOME/.pgpass" ]] && grep -qF "$PGHOST:$PGPORT:$PGDATABASE:$PGUSER:" "$HOME/.pgpass"; then
    say "password: matching line found in ~/.pgpass — psql will use it."
  else
  # Passed as PGPASSWORD, not inside a URL: a password with @ : / or % breaks a
  # connection string silently and there is nothing to percent-encode here.
  for _try in 1 2 3; do
    ask_secret PGPASSWORD "Supabase database password (will not echo):"
    [[ -n "$PGPASSWORD" ]] && break
    warn "read succeeded but returned 0 characters — a blank line, not EOF."
    note "If you cannot see your cursor in this window, your keystrokes are going"
    note "somewhere else. The script is waiting on $(tty 2>/dev/null || echo 'this terminal')."
    if [[ $_try == 3 ]]; then
      warn "three tries — stopping."
      note "Skip the prompt entirely. Either create ~/.pgpass (see the comment"
      note "above this block in the script), or run:"
      note "  cd ~/bcns && PGPASSWORD='your-password' ./w3-oauth-wizard.sh"
      exit 1
    fi
  done
  fi
  export PGPASSWORD
fi

say "Connecting to ${PG_TARGET} ..."
pg -v ON_ERROR_STOP=1 -tAc 'select 1' >/dev/null \
  || { warn "could not connect — wrong password, or the project is paused."; exit 1; }
say "connected."
echo

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Droplet preflight — read the gate as it is now" 3
say "oauthEnabled() needs BOTH the approval list AND the Shopify credentials"
say "(lib/oauth-config.ts:37). Checking the credentials are really there."
echo
ask DROPLET_SSH "Droplet ssh target [root@146.190.138.141]:"
DROPLET_SSH="${DROPLET_SSH:-root@146.190.138.141}"
ask SSH_KEY "Private key for it [~/.ssh/id_ed25519_bcns]:"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/id_ed25519_bcns}"
SSH_KEY="${SSH_KEY/#\~/$HOME}"
[[ -f "$SSH_KEY" ]] || { warn "no such key: $SSH_KEY"; exit 1; }

# Prove the login before anything depends on it, so a key problem reads as a key
# problem instead of "could not read /srv/connect/env".
WHO="$(dssh 'id -un' 2>/dev/null | tr -d '[:space:]' || true)"
if [[ -z "$WHO" ]]; then
  warn "ssh ${DROPLET_SSH} with ${SSH_KEY} failed."
  note "The two routes that work (baselines/2026-09-15/pv1-gates/chunk2-droplet.txt):"
  note "  root@146.190.138.141     -> ~/.ssh/id_ed25519_bcns"
  note "  connect@146.190.138.141  -> ~/.ssh/id_ed25519_bcns_deploy"
  exit 1
fi
say "ssh ok, logged in as: ${WHO}"

say "Env keys present on the droplet (names only, no values):"
dssh 'grep -oE "^[A-Z_]+=" /srv/connect/env | tr -d "="' || {
  warn "could not read /srv/connect/env"; exit 1; }
echo
note "SHOPIFY_CLIENT_SECRET must appear above. OAUTH_APPROVED_SOURCES must NOT."
echo
# The client id is public, so printing it costs nothing and catches the droplet
# pointing at the WRONG APP (e.g. bcns-data). That failure otherwise surfaces
# only as a generic connect-failed after the gate is already open.
say "Droplet SHOPIFY_CLIENT_ID vs. the Dev Dashboard:"
# || true: pipefail would abort the script on a missing key, skipping the
# "(unset)" branch below that actually explains the problem.
DROPLET_CLIENT_ID="$(dssh 'grep -oE "^SHOPIFY_CLIENT_ID=.*" /srv/connect/env | cut -d= -f2-' | tr -d '[:space:]' || true)"
say "  droplet:   ${DROPLET_CLIENT_ID:-(unset)}"
say "  dashboard: ${APP_CLIENT_ID}"
if [[ "$DROPLET_CLIENT_ID" == "$APP_CLIENT_ID" ]]; then
  say "  match."
else
  warn "MISMATCH — the hub is configured for a different Shopify app."
  warn "Fix /srv/connect/env before opening the gate. Stopping."
  exit 1
fi
echo
say "Gate as it stands (signed-out probe):"
say "  $(probe_gate)"
note "expected: OAUTH_APPROVED_SOURCES unset (gate CLOSED) — shipping dark."
pause "Match? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Open the gate" 2
warn "This makes self-serve Shopify live on production. Stage 7 reverts it."
warn "Shipping dark is intended until W6 — it must not stay open."
confirm "Append OAUTH_APPROVED_SOURCES=shopify and restart the hub?" \
  || { say "gate left closed."; exit 0; }

# restart, not reload: systemd reads EnvironmentFile only at process start
# (infra/bcns-app@.service:14). The unit file itself is unchanged, so no daemon-reload.
dssh 'printf "OAUTH_APPROVED_SOURCES=shopify\n" >> /srv/connect/env \
  && sudo -n systemctl restart bcns-app@connect && sleep 2 && systemctl is-active bcns-app@connect'
GATE_FLIPPED=1
echo
say "Gate now:"
say "  $(probe_gate)"
note "expected: OAUTH_APPROVED_SOURCES=shopify, on a NEW pid. Same pid = no restart."
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Do the install" 8
ask DEV_SHOP "Development store domain [${DEFAULT_SHOP}]:"
DEV_SHOP="${DEV_SHOP:-$DEFAULT_SHOP}"
DEV_SHOP="${DEV_SHOP%%/*}"; DEV_SHOP="${DEV_SHOP#https://}"
echo
say "In a SECOND terminal, tail the hub log — the browser only ever shows"
say "'connect-failed', the real reason is logged server-side (callback/route.ts:60):"
echo
note "  ssh -i ${SSH_KEY} ${DROPLET_SSH} 'journalctl -u bcns-app@connect -f -n 0'"
echo
step "Sign in at ${HUB} as smoke+${SLUG}@bcn-services.com"
step "Confirm the header (top right) reads 'bcns OAuth Test' — NOT SaunaBoy."
step "On the Shopify card, click Connect, enter ${DEV_SHOP}, approve on Shopify."
open_url "${HUB}"
echo
note "Version bcns-connect-4 asks for exactly the 7 scopes in SHOPIFY_SCOPES —"
note "verified against the Dev Dashboard, so a missing_scopes refusal is unlikely."
note "If one still appears, read the journalctl line: handleTokenResponse"
note "(shopify-oauth.ts:213) names the exact scope Shopify withheld."
pause "Install finished (success or failure)? Press Enter."

echo
say "data.source_tokens — done-criterion row 1:"
pg -c \
  "select c.slug, t.source, t.kind, t.status, t.status_detail, t.created_at
     from data.source_tokens t join data.clients c on c.id = t.client_id
    where c.slug='${SLUG}'"
say "data.connector_schedule — done-criterion row 2:"
pg -c \
  "select c.slug, s.source, s.interval, s.backfill_from, s.config, s.enabled, s.next_run_at
     from data.connector_schedule s join data.clients c on c.id = s.client_id
    where c.slug='${SLUG}'"
note "Both empty = the install did not complete. Read the journalctl line and stop here."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Auth probe against the stored token" 3
say "checklist() is only ever called from onboard.ts:70 — the CLI path — so the"
say "OAuth flow never runs it. This sends the same query by hand (checklist.ts:31),"
say "using the token the callback stored, which is what the criterion actually asks."
echo
STORED_TOKEN="$(pg -tAc \
  "select t.secret from data.source_tokens t join data.clients c on c.id=t.client_id
    where c.slug='${SLUG}' and t.source='shopify'" | tr -d '[:space:]' || true)"
if [[ -z "$STORED_TOKEN" ]]; then
  warn "no stored token — the install didn't write one. Stop here."
  exit 1
fi
note "token read from the database (not shown)"
echo
say "RAW response:"
shop_gql "$STORED_TOKEN" '{ currentAppInstallation { accessScopes { handle } } shop { ianaTimezone currencyCode } }'
echo
note "accessScopes is the authoritative list of what the merchant actually granted."
note "A shop{} block present = the probe passes = done-criterion 3 met."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Settle read_inventory" 8
warn "BLOCKED as authored. Shopify stopped merchants creating new legacy custom"
warn "apps on 2026-01-01, so the two hand-minted tokens below cannot be made."
note "The empirical A/B now needs a second OAuth install with read_inventory"
note "removed from SHOPIFY_SCOPES, i.e. a code change and a redeploy between the"
note "two installs. That is its own window, not this one."
echo
if ! confirm "Try the two-token route anyway (say no to skip this stage)?"; then
  SKIPPED+=("read_inventory unsettled — legacy custom apps banned; needs a 2nd install with a narrowed scope list")
  say "skipped."
else
say "Question: does ProductVariant.inventoryQuantity need read_inventory, or does"
say "read_products alone return it? shopify.ts:95 reads 'inventoryQuantity ?? 0',"
say "so a missing scope shows up as a silent zero. We read the RAW response."
echo
say "Rather than editing SHOPIFY_SCOPES and redeploying, mint two tokens by hand:"
step "Dev store admin → Settings → Apps and sales channels → Develop apps"
step "App A: Admin API scopes = read_products AND read_inventory. Install, copy token."
step "App B: Admin API scopes = read_products ONLY. Install, copy token."
open_url "https://admin.shopify.com/store/${DEV_SHOP%%.*}/settings/apps/development"
echo
note "Assumption being tested: Shopify's field-level permissions don't depend on"
note "how the token was minted. If A and B differ, that assumption held."
echo
ask_secret TOKEN_WITH "Token A (WITH read_inventory):"
ask_secret TOKEN_WITHOUT "Token B (WITHOUT read_inventory):"

for label in WITH WITHOUT; do
  if [[ "$label" == "WITH" ]]; then tok="$TOKEN_WITH"; else tok="$TOKEN_WITHOUT"; fi
  echo
  printf '  %s─── %s read_inventory ───%s\n' "$BOLD" "$label" "$RESET"
  say "granted scopes (RAW):"
  shop_gql "$tok" '{ currentAppInstallation { accessScopes { handle } } }'
  echo
  say "Q_INVENTORY, verbatim from shopify.ts:55 (RAW):"
  shop_gql "$tok" 'query I($after:String){products(first:50,after:$after){pageInfo{hasNextPage endCursor}nodes{id variants(first:100){nodes{inventoryQuantity}}}}}'
  echo
done
note "This store's catalog has real, varied stock (50 / 100 / 20 units) AND one"
note "genuinely zero item ('The Out of Stock Snowboard'). A single 0 is therefore"
note "not evidence of a missing scope — only an ALL-zero or null body is."
echo
note "Compare the two RAW bodies, not any total. Three outcomes:"
note "  same numbers          → read_inventory is unnecessary, drop it"
note "  B nulls or ACCESS_DENIED → the scope is required, keep it"
note "  B all zeros           → also required; this is the silent-zero case"
note "If dropping it: edit SHOPIFY_SCOPES in apps/connect/lib/shopify-oauth.ts:32"
note "AND platform/scripts/checklist.ts:12 — the checklist refuses a short token."
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Tear down" 4
warn "Two reverts. Do both."
echo
if confirm "1/2 — close the OAuth gate on the droplet (back to shipping dark)?"; then
  dssh 'sed -i "/^OAUTH_APPROVED_SOURCES=/d" /srv/connect/env \
    && sudo -n systemctl restart bcns-app@connect && sleep 2 && systemctl is-active bcns-app@connect'
  GATE_FLIPPED=0
  say "Gate now:"
  say "  $(probe_gate)"
  note "must read: OAUTH_APPROVED_SOURCES unset (gate CLOSED), on a new pid."
else
  SKIPPED+=("OAuth gate LEFT OPEN on the droplet — revert before W6")
  warn "gate left open."
fi
echo
if confirm "2/2 — delete the ${SLUG} client and its rows?"; then
  # source_tokens and connector_schedule cascade from data.clients, but the
  # canonical tables (data.customers, data.jobs, ...) reference clients with NO
  # cascade (schema.sql:235+). So if the worker ingested anything for this
  # client, the client delete throws a FK violation. Kill the schedule and the
  # token first — that alone removes the SaunaBoy-adjacent risk — then try the
  # client delete without ON_ERROR_STOP so a leftover fact row just reports.
  pg -v ON_ERROR_STOP=1 -q -c \
    "delete from data.connector_schedule where client_id=(select id from data.clients where slug='${SLUG}')" -c \
    "delete from data.source_tokens    where client_id=(select id from data.clients where slug='${SLUG}')"
  say "token + schedule rows deleted."
  if pg -v ON_ERROR_STOP=1 -q -c \
       "delete from data.clients where slug='${SLUG}'" 2>&1; then
    say "client ${SLUG} deleted."
  else
    warn "client row NOT deleted — the worker had already ingested rows for it."
    note "The token is gone, so nothing can ingest further. Clean up at leisure:"
    note "  delete from data.customers where client_id=(select id from data.clients where slug='${SLUG}');"
    note "  ... then retry the data.clients delete."
    SKIPPED+=("client row ${SLUG} still exists — fact rows block the delete")
  fi
  SKIPPED+=("auth user smoke+${SLUG}@bcn-services.com still exists in GoTrue — delete in the Supabase dashboard")
else
  SKIPPED+=("test client ${SLUG} still exists — delete when done")
fi
pause

finish
