#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
GH_REPO="${GH_REPO:-}" # owner/repo for gh writes; empty = infer from cwd
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# _gh_ready — gh installed and authenticated?
_gh_ready() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

# preflight_gh — prove gh can actually reach the repo BEFORE any stage asks for
# a credential. A token that cannot resolve the repo must fail here, not after
# the human has minted a password. Call once, right after banner.
preflight_gh() {
  local out="" rc=0
  if ! command -v gh >/dev/null 2>&1; then
    warn "gh not installed — secrets will be skipped"; return 1
  fi
  if ! gh auth status >/dev/null 2>&1; then
    warn "gh not authenticated — run: gh auth login"; return 1
  fi
  if [[ -n "$GH_REPO" ]]; then
    out=$(gh repo view "$GH_REPO" --json nameWithOwner 2>&1 >/dev/null) || rc=$?
  else
    out=$(gh repo view --json nameWithOwner 2>&1 >/dev/null) || rc=$?
  fi
  (( rc == 0 )) && return 0
  warn "gh cannot reach ${GH_REPO:-the current repo}: ${out%%$'\n'*}"
  note "fix the token scope now, or every secret below will be skipped"
  return 1
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh, targeting
# $GH_REPO when set. Reports gh's own error rather than hiding it: a silent
# "skipped" reads as done and is how a wizard finishes with nothing written.
set_secret() {
  local name="$1" value="$2" err="" rc=0
  if ! _gh_ready; then
    err="gh not installed or not authenticated"; rc=1
  elif [[ -n "$GH_REPO" ]]; then
    err=$(printf '%s' "$value" | gh secret set "$name" --repo "$GH_REPO" 2>&1 >/dev/null) || rc=$?
  else
    err=$(printf '%s' "$value" | gh secret set "$name" 2>&1 >/dev/null) || rc=$?
  fi
  if (( rc == 0 )); then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  err="${err%%$'\n'*}"; [[ -n "$err" ]] || err="gh exited $rc"
  SKIPPED+=("GitHub secret $name — $err")
  warn "skipped GitHub secret $name: $err"
  return 0
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2" err="" rc=0
  if ! _gh_ready; then
    err="gh not installed or not authenticated"; rc=1
  elif [[ -n "$GH_REPO" ]]; then
    err=$(gh variable set "$name" --repo "$GH_REPO" --body "$value" 2>&1 >/dev/null) || rc=$?
  else
    err=$(gh variable set "$name" --body "$value" 2>&1 >/dev/null) || rc=$?
  fi
  if (( rc == 0 )); then
    printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  err="${err%%$'\n'*}"; [[ -n "$err" ]] || err="gh exited $rc"
  SKIPPED+=("GitHub variable $name — $err")
  warn "skipped GitHub variable $name: $err"
  return 0
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Nothing here touches .env — the Shopify app secret must never land on disk.
# Pointing ENV_FILE at a path that cannot exist also stops ask/ask_secret from
# offering a stale value as a default.
ENV_FILE=/nonexistent/.env

PROJECT=bcns-leads
REGION=us-east4
JOB=bcns-data-worker
RUNTIME="bcns-data-worker@${PROJECT}.iam.gserviceaccount.com"
SECRET=SHOPIFY_CLIENT_SECRET
# Public value, committed in apps/connect/shopify.app.toml (app 425274376193, "bcns Connect").
CLIENT_ID_DEFAULT=a87d4fe4a4c2b0a57d370e24f28a12bf

TOTAL_STAGES=4
TOTAL_MINUTES=7

banner "Shopify credentials for the bcns-data worker"

# ── 1. gcloud can reach the project ───────────────────────────────────────
stage "gcloud — sign in to the project" 2
say "The worker lives in the GCP project ${PROJECT}. This stage only checks access."
command -v gcloud >/dev/null 2>&1 || {
  warn "gcloud is not installed. Install the Google Cloud CLI, then re-run this script."
  exit 1
}

# Always print the real gcloud error. An earlier version of this script claimed
# "your session has expired" for every failure, which hid a wrong project, a
# missing role and a dead token behind one misleading sentence.
reach_job() {
  REACH_ERR=$(gcloud run jobs describe "$JOB" \
    --project "$PROJECT" --region "$REGION" --format='value(metadata.name)' 2>&1 >/dev/null)
}

note "account:  $(gcloud config get-value account 2>/dev/null || echo '(none)')"
note "target:   job ${JOB} in project ${PROJECT}, region ${REGION}"
printf '\n'

if ! reach_job; then
  warn "gcloud could not read the job. Its exact words:"
  printf '\n%s\n\n' "$REACH_ERR"
  case "$REACH_ERR" in
    *Reauthentication*|*"auth login"*|*credentials*|*"invalid_grant"*|*UNAUTHENTICATED*)
      say "This is an expired sign-in. I can refresh it right here."
      if confirm "run gcloud auth login now"; then
        gcloud auth login || true
      else
        warn "run 'gcloud auth login' yourself, then re-run this script."
        exit 1
      fi
      ;;
    *NOT_FOUND*|*"not found"*)
      warn "The job does not exist under that project/region. Nothing here can fix that."
      note "List what is there:  gcloud run jobs list --project ${PROJECT} --region ${REGION}"
      exit 1
      ;;
    *PERMISSION_DENIED*|*"does not have permission"*|*forbidden*)
      warn "Your account is authenticated but lacks Cloud Run read access on ${PROJECT}."
      note "Check which account is active:  gcloud auth list"
      exit 1
      ;;
    *)
      warn "Unrecognised failure. Fix what the message above says, then re-run."
      exit 1
      ;;
  esac
  if ! reach_job; then
    warn "Still cannot read the job after signing in:"
    printf '\n%s\n\n' "$REACH_ERR"
    note "Active accounts:"
    gcloud auth list 2>&1 | sed 's/^/    /'
    exit 1
  fi
fi
note "reached ${JOB} in ${PROJECT}/${REGION}."

# ── 2. Read both values off the Shopify Partner dashboard ─────────────────
stage "Shopify Partners — client credentials" 3
say "Both values come from the one Shopify app that every merchant installs."
open_url "https://partners.shopify.com/"
step "Sign in as the bcns Partner organization (bcn-services.com)."
step "Left nav: Apps → open the app whose redirect URL is connect.bcn-services.com."
note "docs/architecture/chunk5-dashboard-steps.md suggests the name bcns Connect; the redirect URL is the reliable identifier."
step "Open 'App setup' → 'Client credentials'."
note "the Client ID is already known from apps/connect/shopify.app.toml — press Enter to accept it."
printf '  %sClient ID [%s]:%s ' "$BOLD" "$CLIENT_ID_DEFAULT" "$RESET"
read -r SHOPIFY_CLIENT_ID || true
SHOPIFY_CLIENT_ID="${SHOPIFY_CLIENT_ID:-$CLIENT_ID_DEFAULT}"
[[ -n "$SHOPIFY_CLIENT_ID" ]] || { warn "the Client ID is required."; exit 1; }
step "Click 'Show' on the Client secret row, then copy it."
note "the next prompt hides what you type; nothing is echoed, logged or written to disk."
ask_secret SHOPIFY_CLIENT_SECRET "Paste the Client secret:"
[[ -n "$SHOPIFY_CLIENT_SECRET" ]] || { warn "the Client secret is required."; exit 1; }

# ── 3. Store the secret and let the worker read it ────────────────────────
stage "Secret Manager — store the app secret" 1
if gcloud secrets describe "$SECRET" --project "$PROJECT" >/dev/null 2>&1; then
  say "${SECRET} already exists. Adding a new version keeps the old one for rollback."
  if confirm "add a new version of ${SECRET}"; then
    printf '%s' "$SHOPIFY_CLIENT_SECRET" |
      gcloud secrets versions add "$SECRET" --project "$PROJECT" --data-file=- >/dev/null
    note "added a new version of ${SECRET}."
  else
    note "kept the existing ${SECRET} value."
  fi
else
  printf '%s' "$SHOPIFY_CLIENT_SECRET" |
    gcloud secrets create "$SECRET" --project "$PROJECT" \
      --replication-policy automatic --data-file=- >/dev/null
  note "created ${SECRET}."
fi
unset SHOPIFY_CLIENT_SECRET   # out of the shell the moment it is stored
# Idempotent: the job's runtime service account is the only principal that reads it.
gcloud secrets add-iam-policy-binding "$SECRET" --project "$PROJECT" \
  --member "serviceAccount:${RUNTIME}" --role roles/secretmanager.secretAccessor >/dev/null
note "${RUNTIME} can read ${SECRET}."

# ── 4. Attach both to the Cloud Run job, then read it back ────────────────
stage "Cloud Run — attach the credentials to the job" 1
say "--update-* merges into the job's existing environment. --set-* would replace all of it."
confirm "update the ${JOB} job now" || { warn "nothing changed."; exit 1; }
gcloud run jobs update "$JOB" --project "$PROJECT" --region "$REGION" \
  --update-env-vars "SHOPIFY_CLIENT_ID=${SHOPIFY_CLIENT_ID}" \
  --update-secrets "${SECRET}=${SECRET}:latest" >/dev/null
note "job updated. Reading it back from the live job:"
printf '\n'
# yaml + grep rather than a --format path: the path differs between gcloud versions,
# and a silently empty result would look like a successful check.
JOB_YAML=$(gcloud run jobs describe "$JOB" --project "$PROJECT" --region "$REGION" --format=yaml)
printf '%s\n' "$JOB_YAML" | grep -i -A2 'shopify' ||
  warn "no Shopify entries came back — check the job by hand."
printf '\n'
say "Image currently running:"
printf '%s\n' "$JOB_YAML" | grep -m1 -E '^\s+image:' || warn "could not read the image."
note "if that still says us-docker.pkg.dev/cloudrun/container/job, no real deploy has landed yet."

finish
say "Next: reconnect one store through the hub, then wait 61 minutes."
say "A worker run after that hour proves the refresh works end to end."
